const types = {
  LOAD_POKEMONS: "LOAD_POKEMONS",
  SAVE_POKEMONS: "SAVE_POKEMONS",
  POKEMONS_LOADING: "POKEMONS_LOADING",
  POKEMON_TYPES_LOADING: "POKEMON_TYPES_LOADING",
  LOAD_POKEMON_TYPES: "LOAD_POKEMON_TYPES",
  SAVE_POKEMON_TYPES: "SAVE_POKEMON_TYPES",
  SET_FILTER: "SET_FILTER",
};

export default types;
